// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSharpReadAssist
{
    internal sealed partial class Vsix
    {
        public const string Id = "CSharpReadAssist.765c8de5-578a-45ce-be27-c8ef97656995";
        public const string Name = "CSharpReadAssist";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "0.2";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
